logging:
  level:
    root: INFO
    com.example.library: TRACE

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  build:
    artifact: @project.artifactId@
    java-version: @java.version@
  app:
    name: 'Task4'
    description: 'This is custom info endpoint'
    author: 'Pavlo Khodachok'

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/springTestDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
    username: 'root'
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    show-sql: true
