server:
  error:
    include-message: always
    include-exception: false
    include-binding-errors: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  build:
    artifact: @project.artifactId@
    java-version: @java.version@
  app:
    name: 'Task4'
    description: 'This is custom info endpoint'
    author: 'Pavlo Khodachok'
